{"uuid": "1ab846f7-e104-4748-8835-f38d0043746d", "children": ["f0747cf8-8b0b-4be4-b078-4e85cd75ff5b", "2a79522f-e8cb-4d31-9f13-bc06187afaf5", "3a88c53f-1b25-4b3c-b764-64775a99f07f"], "befores": [{"name": "test_edit", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=92.0.4515.107)\n\n", "trace": "  File \"C:\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\pycharm\\Automation_project\\testcases\\conftest.py\", line 19, in test_edit\n    browser.maximize_window()\n  File \"C:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 737, in maximize_window\n    self.execute(command, params)\n  File \"C:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1629176985303, "stop": 1629176987518}, {"name": "test_edit", "status": "passed", "start": 1629176987690, "stop": 1629176990395}], "afters": [{"name": "test_edit::0", "status": "passed", "start": 1629176993240, "stop": 1629176995350}], "start": 1629176987690, "stop": 1629176995350}